### ISSUE TITLE
Use CONSUMER_KEY & CONSUMER_SECRET as env for TwitterProvider

### ISSUE THREAD

**Issue by deadcoder0904** [nextauthjs/docs#56]
### Description 📓

Using CONSUMER_KEY & CONSUMER_SECRET is less confusing to beginners.

Currently, TWITTER_ID & TWITTER_SECRET is used but Twitter refers to it as CONSUMER_KEY & CONSUMER_SECRET so I think that is the way to go, especially for beginners.

### How to reproduce ☕️

See how Twitter refers to it → https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR

**Comment by deadcoder0904** [comment]
Ha didn't know there was a different repo.

I'd argue that every provider should have their own naming because right now, I'm implementing Twitter & I was confused whether or not, I was using correct `.env` variables. That's why my issues popped up.

**Comment by balazsorban44** [comment]
Yes, that's why I suggested adding a comment to the docs. :slightly_smiling_face: 

Most people won't care about naming conventions for particular providers, we are a library that abstracts away as much as possible (gradually allowing you to override any config).

Apart from that, as I mentioned literally every other OAuth provider we have built-in uses the naming ID and SECRET, so nothing would change for them.

**Comment by deadcoder0904** [comment]
> The only outlier from OAuth 2 is Twitter.

lmfao 😂

Twitter is weird but that's the only one I'm interested in (at least right now).

PR sent #57 :)

**Comment by balazsorban44** [comment]
So I actually checked this, and it is really referred to as API key, and API key secret:
![image](https://user-images.githubusercontent.com/18369201/135713229-cf45cdf0-e467-41f5-b2ca-d832292c3dce.png)

**Comment by balazsorban44** [comment]
There is also this under [terminology](https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens) though:
![image](https://user-images.githubusercontent.com/18369201/135713254-bf328c27-d9a4-44a9-b257-76df159819d9.png)

**Comment by balazsorban44** [comment]
I would suggest that we link to this section from the tip in your PR

**Comment by deadcoder0904** [comment]
Yeah, I did too before posting the issue. See https://developer.twitter.com/en/docs/authentication/oauth-1-0a/obtaining-user-access-tokens

<img width="703" alt="Screenshot 2021-10-02 at 4 27 26 PM" src="https://user-images.githubusercontent.com/16436270/135713269-e6c64b38-31d6-47e1-844d-a1d66cab71b7.png">

Also, all the Twitter clients use `CONSUMER_*` term as well.

**Comment by deadcoder0904** [comment]
Even this one I'm using mentions `CONSUMER_*` term → https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/auth.md#create-the-auth-link

<img width="1045" alt="Screenshot 2021-10-02 at 4 44 44 PM" src="https://user-images.githubusercontent.com/16436270/135713752-4c5421a6-7973-4689-9624-630cba149dee.png">

**Comment by ndom91** [comment]
Hey yall, so i see your point that others are using the consumer terminology, but Twitter seems to have migrated since to use the api_key, etc. nomenclature. 

We want as much as possible to keep the providers in sync. Twitter being the only one that still uses oauthv1 might just need some more clarification in the docs. 

But I wouldn't go by what other libraries are doing. Let's stick to what we have with other providers and potentially translate to what Twitter refers to in their key setup area, api key and api key secret. 

Does that make sense?

**Comment by deadcoder0904** [comment]
@ndom91 Agreed on that. Twitter will soon release Oauth 2.0 too so it might use the new nomenclature. Merge the PR or close it :)

**Comment by balazsorban44** [comment]
Do you have any ETA/information on when Twitter would release OAuth 2.0? 😮 I haven't found anything on that yet.

**Comment by deadcoder0904** [comment]
Nope, but it's gonna be very slow. They started it 1-2 years ago & it's still not finished so I guess maybe 1-2 years more.

Here's their Roadmap → https://trello.com/b/myf7rKwV/twitter-developer-platform-roadmap

**Comment by balazsorban44** [comment]
If that's the case, we might have to make OAuth1 support opt-in... We ship even v4 with `node-oauth` https://github.com/ciaranj/node-oauth#readme just for the sake of Twitter. But everyone else has to download it too...

In v5, I think we'll refactor things to reduce the bundle size.

**Comment by balazsorban44** [comment]
https://twittercommunity.com/t/announcing-oauth-2-0-beta/159189 :eyes:
