### ISSUE TITLE
Model schema not correct

### ISSUE THREAD

**Issue by lughino** [nextauthjs/docs#96]
Hi there,

I'm working on implementing next-auth v4, and I found the schema model image in the doc https://next-auth.js.org/adapters/models not correct.
There are fields that cannot be set as `NOT NULL`.
I found `refresh_token`, `scope`, `oauth_token_secret`, `oauth_token`, and `session_state` to be set as `NULL` as some provider (e.g. Twitter) does not send some of those fields.
Could you kindly update the documentation to reflect the real schema?
Thanks

**Comment by balazsorban44** [comment]
Twitter is a special one amongst all the OAuth Providers we support. It still uses the OAuth 1 spec, which means it returns `oauth_token` and `oauth_token_secret`, and none of the usual ones likes `access_token`, `refresh_token`, etc. Since Twitter is an outlier amongst all of our providers.

If you know that you won't need to use OAuth 2 specific fields, you can safely ignore them from your database model. however, if you use multiple providers (eg GitHub and Twitter), you might need all those different fields.
